plugins {
    id 'java-library'
    id 'maven-publish'
	id 'io.github.0ffz.github-packages' version '[1,2)'
    id 'net.neoforged.moddev' version '1.0.23'
    id "me.modmuss50.mod-publish-plugin" version "2.1.1"
}

tasks.named('wrapper', Wrapper).configure {
	distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
	mavenLocal()
	mavenCentral()
	maven { 
		url = "https://api.modrinth.com/maven"
	}
	maven {
		url = "https://modmaven.dev"
	}
	maven {
		name = "Fuzs Mod Resources"
		url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
	}
    maven { url = "https://api.modrinth.com/maven" }
    maven {
        url "https://cursemaven.com"
    }
}

base {
	archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
	version = project.neo_version

	parchment {
		mappingsVersion = project.parchment_mappings_version
		minecraftVersion = project.parchment_minecraft_version
	}

	runs {
		client {
			client()
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		server {
			server()
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		gameTestServer {
			type = "gameTestServer"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		data {
			data()
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
		}

		configureEach {
			systemProperty 'forge.logging.markers', 'REGISTRIES'
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

dependencies {
	implementation "net.neoforged:neoforge:${neo_version}"

	// Iris Shaders (only needed for shader test, api is identical to oculus)
	compileOnly("maven.modrinth:iris:1.8.1+1.21.1-neoforge")

	// compile against the JEI API but do not include it at runtime
	compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
	// at runtime, use the full JEI jar
	runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    implementation "maven.modrinth:jade:${project.jade_version}"


    //implementation "maven.modrinth:midnightlib:${project.midnightlib_version}"
    implementation "curse.maven:midnightlib-488090:6222973"
    jarJar ("maven.modrinth:midnightlib:${project.midnightlib_version}")

	api "fuzs.puzzleslib:puzzleslib-neoforge:21.1.36"
	jarJar "fuzs.puzzleslib:puzzleslib-neoforge:21.1.36"

	api "fuzs.limitlesscontainers:limitlesscontainers-neoforge:21.1.0"
	jarJar "fuzs.limitlesscontainers:limitlesscontainers-neoforge:21.1.0"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
	var replaceProperties = [
		minecraft_version : minecraft_version,
		minecraft_version_range : minecraft_version_range,
		neo_version : neo_version,
		neo_version_range : neo_version_range,
		loader_version_range : loader_version_range,
		midnightlib_version : midnightlib_version,
		mod_id : mod_id,
		mod_name : mod_name,
		mod_license : mod_license,
		mod_version : mod_version,
		mod_authors : mod_authors,
		mod_description : mod_description
	]
	inputs.properties replaceProperties
	expand replaceProperties
	from "src/main/templates"
	into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
	publications {
		register('mavenJava', MavenPublication) {
			from components.java
		}
	}
	repositories {
		maven {
			url "file://${project.projectDir}/repo"
		}
	}
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

	// Enable linting 
	// TODO: Add '-Werror' flag, to turn warnings into errors
	options.compilerArgs += ['-Xlint:all']
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}

publishMods {
    changelog = "# Markdown changelog content"
    type = STABLE

    file = jar.archiveFile

    curseforge {
        projectId = "1096362"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add("1.21.1")
        client = true
        server = true
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = "tn8wGyDx"
        minecraftVersions.add("1.21.1")
    }
}
